[mcp_servers.playwright-test]
command = "npx"
args = ["playwright", "run-test-mcp-server"]

[mcp_servers.angular-cli]
command = "npx"
args = ["-y", "@angular/cli@latest", "mcp", "-E", "modernize"]

[mcp_servers.webstorm]
command = "/Users/hedde/Applications/WebStorm.app/Contents/jbr/Contents/Home/bin/java"
args = ["-classpath","/Users/hedde/Applications/WebStorm.app/Contents/plugins/mcpserver/lib/mcpserver-frontend.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/util-8.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.ktor.client.cio.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.ktor.client.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.ktor.network.tls.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.ktor.io.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.ktor.utils.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.kotlinx.io.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.kotlinx.serialization.core.jar:/Users/hedde/Applications/WebStorm.app/Contents/lib/module-intellij.libraries.kotlinx.serialization.json.jar","com.intellij.mcpserver.stdio.McpStdioRunnerKt"]

[mcp_servers.webstorm.env]
IJ_MCP_SERVER_PORT = "64343"

